package random;

/**
 * Generates a number randomly distributed between 0 and 1 Uses mixed LCG
 * 
 * @author ahmed
 *
 */
public class RandomGenerator
{
	/* fields */
	long a, c, m;
	long x;

	public RandomGenerator()
	{
		// period size = 33554431
		m = 1l << 25;

		// c is generated by system time, and make sure it is odd(relatively
		// prime to m)
		c = System.nanoTime() % m;
		if (c % 2 == 0)
			c--;

		// a = 1 + 4k, k = 10 ^ 8
		a = 1l + 4l * 100000000;

		// seed is generated by system time
		x = System.nanoTime() % m;
	}

	/**
	 * @return the next random number between 0 and 1
	 */
	public double nextRand()
	{
		x = (a * x + c) % m;
		return 1.0 * x / m;
	}

}
